### PR TITLE
application start up code changes

### PR DESCRIPTION
**Pull request by jaykay99992**
I changed the function startsWith() to contain() , in case the os name does not start with exactly the key words "win" or "mac" .

I also removed the if "win" condition because the windows application will launch either way if the os name does not match the conditions

### CODE REVIEW

**Comment by myriamgallant** [comment]
Good solution.
Consider adding brief comments to help future maintainers :
- Explaining the reason for the change from startsWith() to contains().
- Explaining windows application will lauch regardless of the specific OS name, so no condition needed.

**Comment by Araisite** [comment]
> Good solution. Consider adding brief comments to help future maintainers :
> 
> * Explaining the reason for the change from startsWith() to contains().
> * Explaining windows application will lauch regardless of the specific OS name, so no condition needed.

I agree, comments are really importante to understand the changement for future maintainers

**Comment by jaykay99992** [comment]
@myriamgallant @Araisite Thank you for the remarks guys, do I proceed and merge it like this with the new comments? is it fine?

**Comment by jaykay9999** [comment]
Code merged

**Pull request merged**
