### PR TITLE
added else statement, and reduced the number of returns

### PR DESCRIPTION
**Pull request by jaykay99992**
Removed return statements inside the if conditions, and added an else statement to help with error detection and handling.

### CODE REVIEW

**Review by danlan21 — CHANGES_REQUESTED** [review]
There is no need to add clutter to the code by adding variable assignments, since all this method does if verify conditions and return a result.
Let's reject these changes and rather refactor the conditional structure of this method, to avoid nesting complex conditional statements.

**Comment by jaykay99992** [comment]
@danlan21 I just got it back to the original way of early return inside if conditions, and I also refactored the condition statements for less nesting, is it good like this ? should I merge it ?

**Comment by danlan21** [comment]
That looks good to me, we can merge this now!

**Comment by jaykay9999** [comment]
Sure, code merged

**Pull request merged**
