### PR TITLE
turned multiple if's to if else statements

### PR DESCRIPTION
**Pull request by jaykay99992**
I noticed that multiple if statements for conditions that cover null , or NOT null, therefore I refactored it to multiple if , else statements.

### CODE REVIEW

**Review by allo-kun — CHANGES_REQUESTED** [review]
The changes modify the behavior of the code. The if(!= null) checks before were useless because the variables are always initialized if null before reaching "// Insert standard menus into menu bar". By moving them into else blocks, the code which would always have run will no longer when the variables are null. The simple fix is to remove the else blocks and just run the code after the if blocks.
`if (fileMenu == null) {
    fileMenu = createFileMenu(v);
}
mb.add(fileMenu, 0);
if (editMenu == null) {
...`
or leave the code as it was before, but remove the if(X != null) checks and just do the adding outside of the unnecessary conditionals.

**Comment by jaykay99992** [comment]
@allo-kun makes sense, I removed the else statement since since mb.add() is going to happen either way. I used the logic you gave me `if (fileMenu == null) { fileMenu = createFileMenu(v); } mb.add(fileMenu, 0); if (editMenu == null) { ...`
Should I merge it like this ? is it fine ?

**Review by allo-kun — APPROVED** [review]
Yup all good!

**Comment by jaykay9999** [comment]
Code approved and merged

**Pull request merged**
