### PR TITLE
Changed fork licence

### PR DESCRIPTION
**Pull request by jaykay99992**
Changed the LGPL license to MIT to allow more flexibility

### CODE REVIEW

**Comment by Mylene599** [comment]
MIT License is a good choice if your objectives are:
- allow a larger flexibility for final users or developers
- get compatibility with other licenses (open source or proprietary)
- encourage more community contributions
- etc

Juste make sure that this license change is conforms to the terms of the original LGPL license and any other contractual obligations.

**Comment by jaykay9999** [comment]
@Mylene599 As for me, I want more contiributors but I also want to see their contributions and added code in their own version if they are going to contribute, should I just go for MIT?

**Comment by Mylene599** [comment]
MIT and GPL may are a good choice for what you need. But there's a difference to consider :

**MIT**
The MIT license may be a good choice because it is permissive and does not have strict restrictions on redistribution or modification of the code. This means that contributors can easily use, modify, and distribute the code, while allowing you to view their contributions before integrating them into the main version of the project. 

But, by default, the license doesn't directly address the issue of wanting to see contributions and added code in their own version before merging them into your project. MIT does not contain specific provisions requiring contributors to make their modified version of the software public or to share their contributions before integrating them into the main project. The MIT license is mainly focused on freedom of use.

However, nothing prevents an MIT-licensed open source project from establishing its own policies and procedures for managing contributor contributions.

**GPL**
If you want to see contributor contributions integrated into a public version of your project while ensuring that those contributions remain open and shared with the community, the GPL license might be a better choice than the MIT license. The GPL is a copyleft license, which means that changes to GPL code must be distributed under the same license terms. This ensures that contributions remain open and users have access to the source code of modified versions.

To keep it simple, you could keep your GPL license. Unless you're up for creating your own policies with MIT.

**Comment by jaykay99992** [comment]
@Mylene599 Sure, I will just reject this and keep it as LGPL for simplicity then

**Comment by jaykay9999** [comment]
pull request rejected to avoid legal issues

**Pull request closed without merging**
