### PR TITLE
removed repetitive comments

### PR DESCRIPTION
**Pull request by jaykay99992**
Removed repeated comments that explains the params m , app , v. Only kept the definitions for the first time they are declared.

I also removed the "mostly used" comments for each method and kept what it does , for code clarity.

### CODE REVIEW

**Comment by Mylene599** [comment]
Variable names lack precision. The need to comment on what a variable represents is a sign that its name is not necessarily appropriate. Normally, we want variable names to be representative of what they represent. m and v are not explicit names and can be detrimental to the readability and the understanding of the code. I recommend calling the variable _m_ menu and _v_ view_menu, for example.

**Comment by jaykay99992** [comment]
@Mylene599 I changed the variable names to something much more clear as you mentioned.  m to menu, v to viewMenu, and app to application. Is it fine like this ? do I merge ?

**Comment by Mylene599** [comment]
Yes you can

**Comment by jaykay9999** [comment]
code approved and merged

**Pull request merged**
